#!/bin/bash

set -euo pipefail

# Script generated by Grok 3 (built by xAI) to manage Helm chart versioning

# Change to parent directory of script using BASH_SOURCE
cd "$(dirname "${BASH_SOURCE[0]}")/.."

# Store Chart.yaml path in variable
CHART_FILE="helm/osm-machinery/Chart.yaml"
VALUES_FILE="helm/osm-machinery/values.yaml"

# Check if on main branch
current_branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$current_branch" != "main" ]; then
    echo "Error: Must be on main branch. Current branch is $current_branch"
    exit 1
fi

# Check if working directory is clean
if [ -n "$(git status --porcelain)" ]; then
    echo "Error: Working directory is not clean. Please commit or stash changes first."
    exit 1
fi

# Get current version from Chart.yaml, handling quoted values
version=$(grep '^version:' "$CHART_FILE" | awk '{print $2}' | tr -d '"')

# Tag current main branch with GPG signature and push tag
git tag -s "v$version" -m "Version $version"

# Bump patch version (e.g., 1.2.3 -> 1.2.4)
new_version=$(echo "$version" | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')

# Update Chart.yaml with new version, preserving quotes if they existed
if grep '^version: "' "$CHART_FILE" > /dev/null; then
    sed -i "s/^version: .*/version: \"$new_version\"/" "$CHART_FILE"
else
    sed -i "s/^version: .*/version: $new_version/" "$CHART_FILE"
fi

for image in \
    maps-tile-uploader \
    maps-tile-server \
; do
    # Update image tags in values.yaml
    sed -i "/^[[:space:]]*repository\:[[:space:]]*cinode\/${image}/{n;s/^\([[:space:]]*\)tag: .*/\1tag: \"$new_version\"/}" "$VALUES_FILE"
done

# Commit the version bump with GPG signature (but don't push)
git add "$CHART_FILE" "$VALUES_FILE"
git commit -S -m "Bump version to $new_version"

echo "Remaining steps:"
echo git push origin "v$version" main
