{{- $dsSetSecret := not $.Values.cinodeUpload.datastore.existingSecret
                    | and ( not ( empty $.Values.cinodeUpload.datastore.value ) )
                    | ternary
                      (
                        $.Values.cinodeUpload.datastore.secretName
                        | default ( print $.Release.Name "-cinode-upload-secret" )
                        | toString
                      )
                      ""
-}}
{{- $wiSetSecret := not $.Values.cinodeUpload.writerInfo.existingSecret
                    | and ( not ( empty $.Values.cinodeUpload.writerInfo.value ) )
                    | ternary
                      (
                        $.Values.cinodeUpload.writerInfo.secretName
                        | default ( print $.Release.Name "-cinode-upload-secret" )
                        | toString
                      )
                      ""
-}}
{{- if $dsSetSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $dsSetSecret | quote }}
type: Opaque
data:
  {{ $.Values.cinodeUpload.datastore.secretKey | quote }}: {{ $.Values.cinodeUpload.datastore.value | b64enc | quote }}
  {{- if $dsSetSecret | eq $wiSetSecret }}
  {{ $.Values.cinodeUpload.writerInfo.secretKey | quote }}: {{ $.Values.cinodeUpload.writerInfo.value | b64enc | quote }}
  {{- end }}
{{- end }}

{{- if $wiSetSecret | and ($wiSetSecret | ne $dsSetSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $wiSetSecret | quote }}
type: Opaque
data:
  {{ $.Values.cinodeUpload.writerInfo.secretKey | quote }}: {{ $.Values.cinodeUpload.writerInfo.value | b64enc | quote }}
{{- end }}
