{{- if $.Values.tileServer.webServer.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ print $.Release.Name "-tile-server-ingress" | quote }}
spec:
  {{- if $.Values.tileServer.webServer.ingress.className }}
  ingressClassName: {{ $.Values.tileServer.webServer.ingress.className | quote }}
  {{- end }}
  rules:
  {{- range $host := $.Values.tileServer.webServer.ingress.hosts }}
  - host: {{ $host | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ print $.Release.Name "-tile-server-svc" | quote }}
            port:
              name: http
  {{- end }}
{{- end }}
