---
apiVersion: v1
kind: Service
metadata:
  name: {{ print $.Release.Name "-tile-server-svc" | quote }}
spec:
  selector:
    app: {{ print $.Release.Name "-tile-server" | quote }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 8642
      targetPort: 8642
      name: expiry
